version: '3'
services:
    web:
        build: .
        ports:
            - "80:80"
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "6379:6379"
    
    
        
        